### ISSUE TITLE
Typescript & Scss variant

### ISSUE THREAD

**Issue by Kukks** [ferrywlto/vdn#9]
I have made a branch which supports typescript and scss @ https://github.com/Kukks/vuejs-aspnetcore-ssr/tree/feature/langspecific

Not sure if you'd be interested in merging it in?

**Comment by Kukks** [comment]
On another note, I've also added in vuex-typex to strongly type the Vuex state management side of things.

**Comment by ferrywlto** [comment]
@Kukks Do you think it is a good idea to fork this repo and apply the typescript stuff? Since moving from js to ts in vue is a bit tricky, if you can fork this repo and have a migration guide then it will be much appreciated for people trying to learn vue step by step. Once they get used to this repo then they can follow to your repo to learn how to do the same thing with typescript instead. I will add a link to your repo once it has been done. :smil

**Comment by ferrywlto** [comment]
@Kukks Just find that you have already forked. I have updated the readme to include link to your repo. 😃
